version: 1
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # "/" will use default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      prod-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
